#!/usr/bin/env python3
from _common import exec_cmd, root

lib = root / 'lib'
ui = lib / 'ui'
output_file = ui / 'ui.g.dart'

# Recursively get all files
def find_ui_files():
  ui_files = []
  for path in ui.rglob('*.dart'):
    if path.is_file():
      ui_files.append(path)
  return ui_files

ui_files = find_ui_files()

code = []
code.append('// GENERATED FILE - DO NOT MODIFY')
code.append('// This file is generated by tool/generate_ui_exports.py')
code.append('')
code.append('// ignore_for_file: unused_import, library_prefixes')

for (i, file) in enumerate(ui_files):
  # exclude generated file
  if file.name == 'ui.gen.dart': continue

  # exclude files under flutter/
  if file.parent.name == 'flutter':
    continue

  lines = []
  with open(file, 'r') as f:
    lines = f.readlines()
  
  # ignore part files
  if not lines: continue
  if (lines[0].startswith('part of ')): continue

  code.append(f'export \'package:musique/ui/{file.relative_to(ui)}\';')
  
code.append('')

with open(output_file, 'w') as f:
  f.write('\n'.join(code))

# Run the dart format command to format the generated file
cmd = f'fvm dart format --line-length 120 {output_file}'
exec_cmd(cmd)